# Generated by Django 4.2.27 on 2025-12-12 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео'), ('poster', 'Афиша')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_uploads/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='user_uploads/videos/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видео в формате MP4', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube видео', null=True),
        ),
    ]
