# Generated by Django 4.2.27 on 2025-12-14 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_userupload_alter_performance_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture.category'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='upload_type',
            field=models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео'), ('poster', 'Афиша'), ('award', 'Награда')], max_length=10),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Фотография награды')),
                ('date', models.DateField(verbose_name='Дата получения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['-date'],
            },
        ),
    ]
