# Generated by Django 4.2.27 on 2025-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_userupload_category_alter_userupload_upload_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео (YouTube, Vimeo, ВКонтакте)', null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_url',
            field=models.URLField(blank=True, help_text='Альтернативная ссылка на видео (для совместимости)', null=True),
        ),
    ]
